language: node_js

sudo: false

node_js: 
  - '10'

cache:
  apt: true
  directories:
      - node_modules

branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  edge: true
  github-token: $GH_TOKEN
  keep-history: true
  commit-message: "Site updated from Travis CI: {{ now('YYYY-MM-DD HH:mm:ss')}}"
  on:
    branch: master
  local-dir: public

