language: node_js

os: linux

node_js: 
  - '10'

cache:
  apt: true
  directories:
      - node_modules

branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  cleanup: false
  edge: true
  token: $GH_TOKEN
  keep_history: true
  commit_message: "Site updated from Travis CI."
  on:
    branch: master
  local_dir: public

