language: node_js

os: linux

node_js: 
  - '10'

cache:
  apt: true
  directories:
      - node_modules

branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

before_deploy:
        - sudo timedatectl set-timezone Asia/Taipei
        - date
        - timedatectl
        - export NOW=$(date +"%Y-%m-%d %H:%m:%S")

deploy:
  provider: pages
  cleanup: false
  edge: true
  strategy: git
  token: $GH_TOKEN
  keep_history: true
  commit_message: "Site updated from Travis CI: $NOW"
  on:
    branch: master
  local_dir: public

